spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/jp
    username: jp
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  liquibase:
    enabled: false
    change-log: liquibase/liquibase-outputChangeLog.xml
#logging:
#  level: debug